#!/bin/sh

# Use git-delta for better diff highlights.
#   https://github.com/dandavison/delta

# Usage:
#   git delta diff ...
#   git delta show ...

# TODO: --color-only

GIT_PAGER="delta --syntax-theme=ansi-light --hunk-style=plain" git "$@"
