#!/bin/sh

# Use git-delta for better diff highlights.
#   https://github.com/dandavison/delta

# Usage:
#   git delta diff ...
#   git delta show ...

# TODO: --color-only

# Sadly --hunk-style=plain is gone.  Consider --color-only?
GIT_PAGER="delta --syntax-theme=gruvbox-light --file-decoration-style='black overline' --hunk-header-decoration-style=''" git "$@"
