#!/bin/sh -x -e
go install github.com/google/codesearch/cmd/...@latest
go install golang.org/x/lint/golint@latest
go install github.com/tobert/pcstat/pcstat@latest
go install github.com/silenceshell/hcache@latest
go install github.com/tomnomnom/gron@latest
go install github.com/shurcooL/markdownfmt@latest
go install github.com/FiloSottile/gorebuild@latest
go install rsc.io/goversion@latest
go install github.com/maruel/panicparse@latest
go install github.com/ChimeraCoder/gojson/gojson@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install mvdan.cc/gofumpt
go install mvdan.cc/gofumpt/gofumports
# github.com/d4l3k/go-pry
# github.com/aclements/go-perf/cmd/memlat
# github.com/fzipp/pythia
# https://github.com/chneukirchen/nq
# https://github.com/sharkdp/bat
# https://github.com/monsterxx03/gospy
