#!/bin/sh -x
set -e

# NOTE: testing on corner
if [ "$(hostid)" = "a8c01401" ]; then
  export GOAMD64=v3
fi

# NOTE: See local version
#go install -x github.com/google/codesearch/cmd/...@latest
go install -x golang.org/x/lint/golint@latest
go install -x github.com/tobert/pcstat@latest
go install -x github.com/tomnomnom/gron@latest
go install -x github.com/shurcooL/markdownfmt@latest
go install -x github.com/FiloSottile/gorebuild@latest
go install -x rsc.io/goversion@latest
go install -x github.com/maruel/panicparse@latest
go install -x github.com/ChimeraCoder/gojson/gojson@latest
go install -x github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install -x mvdan.cc/gofumpt@latest
#gotip install -x mvdan.cc/gofumpt/gofumports@latest
go install -x github.com/yoheimuta/protolint/cmd/protolint@latest
go install -x github.com/go-critic/go-critic/cmd/gocritic@latest
go install -x golang.org/x/tools/cmd/goimports@latest
go install -x honnef.co/go/tools/cmd/staticcheck@latest
go install -x github.com/mgechev/revive@latest
#gotip install -x github.com/silenceshell/hcache@latest
# github.com/d4l3k/go-pry
# github.com/aclements/go-perf/cmd/memlat
# github.com/fzipp/pythia
# https://github.com/chneukirchen/nq
# https://github.com/sharkdp/bat
# https://github.com/monsterxx03/gospy
go install -x github.com/stern/stern@latest
go install -x github.com/wader/fq@latest
go install -x github.com/bufbuild/buf/cmd/buf@latest
go install -x github.com/nsf/gocode@latest
go install -x golang.org/x/vuln/cmd/govulncheck@latest
go install -x github.com/yonahd/kor@latest
go install -x github.com/psanford/wormhole-william@latest
go install -x github.com/kisielk/godepgraph@latest
go install -x github.com/Zxilly/go-size-analyzer/cmd/gsa@latest
go install -x github.com/go-shiori/shiori@latest
go install -x github.com/avitaltamir/cyphernetes/cmd/cyphernetes@latest
go install -x github.com/homeport/dyff/cmd/dyff@latest
go install -x github.com/znscli/zns@latest
